name = "LeanServerWASM"
version = "0.1.0"
defaultTargets = ["LeanServerWASM"]

[[require]]
name = "LeanServer"
git = "https://github.com/AfonsoBitoque/LeanServer"
rev = "main"

[[lean_lib]]
name = "LeanServerWASM"
roots = ["WasmAPI"]
precompileModules = true
